global using Godot;
global using RogueGambit.Managers;
global using RogueGambit.Static.Constants;
global using RogueGambit.Models.State;
global using RogueGambit.Models;
global using System.Collections.Generic;
global using System.Linq;
global using RogueGambit.Managers.Interface;
global using static RogueGambit.Static.Constants.PieceConstants;
global using static RogueGambit.DependencyInjector;
global using static RogueGambit.ServiceLocator;